// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs-cS0BpajCQ-NL9z0ye3ydcJlQ8TxgPA',
    appId: '1:875846569403:web:75dc7575e387f6e96fc89e',
    messagingSenderId: '875846569403',
    projectId: 'mysocialmediaapp-e5ce3',
    authDomain: 'mysocialmediaapp-e5ce3.firebaseapp.com',
    storageBucket: 'mysocialmediaapp-e5ce3.firebasestorage.app',
    measurementId: 'G-YXK44Y69HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxY7CXdbBqyYoDXZjeQ6HP0QnZLpPJBrs',
    appId: '1:875846569403:android:32d02386a007f4896fc89e',
    messagingSenderId: '875846569403',
    projectId: 'mysocialmediaapp-e5ce3',
    storageBucket: 'mysocialmediaapp-e5ce3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs-cS0BpajCQ-NL9z0ye3ydcJlQ8TxgPA',
    appId: '1:875846569403:web:de6dc316b44753ca6fc89e',
    messagingSenderId: '875846569403',
    projectId: 'mysocialmediaapp-e5ce3',
    authDomain: 'mysocialmediaapp-e5ce3.firebaseapp.com',
    storageBucket: 'mysocialmediaapp-e5ce3.firebasestorage.app',
    measurementId: 'G-V2H66GM5GQ',
  );
}
